### ISSUE TITLE
RSS link goes to the wrong place

### ISSUE THREAD

**Issue by veganstraightedge** [gonsie/gonsie.github.io#1]
I found your site via Kottke. (Congrats on that!)

I tried subscribing to your RSS feed, but my Reeder.app got confused on the URL. 

Upon inspection, it looks like it's linked to `/feed.xml` and it should be going to `/blorg/feed.xml`.

Good luck! I look forward to reading more.

**Comment by gonsie** [comment]
Thanks for the issue! `/blorg/feed.xml` is the right link... it's actually a different (private) repo from GitHub which may be why the reader is getting confused. I'll see what I can do.

**Comment by gonsie** [comment]
It should be working now, without all the mangling of different sub-sites.
